// ── Alternatives Database ──────────────────────────────────────────
// Intelligent, structured alternatives engine that matches by flagged
// ingredients, user dietary preferences, and relevance scoring.

import type { ProductResult } from "@/lib/scoring";

export interface AlternativeProduct {
  name: string;
  brand: string;
  score: number;
  category: string;
  subcategory: string;
  fixes: string[];
  keyIngredients: string[];
  avoids: string[];
  certifications: string[];
  whereToFind: string[];
  priceRange: "budget" | "mid" | "premium";
  reason: string;
  imageUrl?: string;
}

// ── Full Database ──────────────────────────────────────────────────
const ALT_DB: Record<string, AlternativeProduct[]> = {
  chips: [
    { name: "Siete Potato Chips", brand: "Siete", score: 82, category: "chips", subcategory: "grain-free", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil", "potatoes", "sea salt"], avoids: ["canola oil", "sunflower oil", "maltodextrin"], certifications: ["Non-GMO", "Grain-Free", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Made with avocado oil instead of canola or sunflower oil.", imageUrl: "https://images.openfoodfacts.org/images/products/085/239/400/0752/front_en.3.400.jpg" },
    { name: "Jackson's Sweet Potato Chips", brand: "Jackson's", score: 79, category: "chips", subcategory: "veggie", fixes: ["Seed Oil"], keyIngredients: ["coconut oil", "sweet potatoes", "sea salt"], avoids: ["canola oil", "soybean oil", "artificial flavors"], certifications: ["Non-GMO", "Paleo", "Vegan"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Cooked in coconut oil with only three clean ingredients." },
    { name: "Kettle Brand Avocado Oil Chips", brand: "Kettle Brand", score: 71, category: "chips", subcategory: "plain", fixes: ["Seed Oil"], keyIngredients: ["avocado oil", "potatoes", "sea salt"], avoids: ["canola oil", "MSG", "artificial colors"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger"], priceRange: "mid", reason: "Uses avocado oil instead of canola with no artificial flavors.", imageUrl: "https://images.openfoodfacts.org/images/products/008/154/300/7943/front_en.3.400.jpg" },
    { name: "Boulder Canyon Chips", brand: "Boulder Canyon", score: 78, category: "chips", subcategory: "plain", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil", "potatoes", "sea salt"], avoids: ["canola oil", "soybean oil", "maltodextrin"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Simple ingredient list with avocado oil and sea salt.", imageUrl: "https://images.openfoodfacts.org/images/products/008/154/300/5918/front_en.3.400.jpg" },
    { name: "Terra Vegetable Chips", brand: "Terra", score: 74, category: "chips", subcategory: "veggie", fixes: ["Ultra-Processed", "Artificial Dye"], keyIngredients: ["sweet potatoes", "taro", "canola oil", "sea salt"], avoids: ["artificial dyes", "maltodextrin", "MSG"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Amazon"], priceRange: "mid", reason: "Real root vegetables with minimal processing and no artificial flavors." },
    { name: "Good Health Avocado Oil Chips", brand: "Good Health", score: 76, category: "chips", subcategory: "plain", fixes: ["Seed Oil"], keyIngredients: ["avocado oil", "potatoes", "sea salt"], avoids: ["canola oil", "sunflower oil", "preservatives"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Clean label with avocado oil and natural seasonings." },
    { name: "Bare Baked Crunchy Apple Chips", brand: "Bare", score: 85, category: "chips", subcategory: "veggie", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["apples"], avoids: ["oil", "sugar", "preservatives"], certifications: ["Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "mid", reason: "Single-ingredient baked apple chips — no oil, sugar, or additives." },
    { name: "Hippeas Organic Chickpea Puffs", brand: "Hippeas", score: 73, category: "chips", subcategory: "grain-free", fixes: ["Seed Oil", "Artificial Dye"], keyIngredients: ["chickpea flour", "sunflower oil", "spices"], avoids: ["canola oil", "artificial colors", "MSG"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic chickpea puffs with no artificial dyes or MSG." },
    { name: "RW Garcia Organic Corn Chips", brand: "RW Garcia", score: 75, category: "chips", subcategory: "plain", fixes: ["Seed Oil", "Artificial Dye"], keyIngredients: ["organic corn", "sunflower oil", "sea salt"], avoids: ["canola oil", "artificial colors", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Organic corn chips with no artificial dyes or seed oils." },
    { name: "Brad's Plant Based Veggie Chips", brand: "Brad's", score: 77, category: "chips", subcategory: "veggie", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["sweet potato", "kale", "red bell pepper"], avoids: ["oil", "artificial flavors", "preservatives"], certifications: ["USDA Organic", "Vegan", "Gluten-Free"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Air-dried vegetables with no added oil or artificial anything." },
  ],
  cereal: [
    { name: "Nature's Path Organic Sunrise", brand: "Nature's Path", score: 85, category: "cereal", subcategory: "flakes", fixes: ["Artificial Dye", "Preservative", "Ultra-Processed"], keyIngredients: ["organic corn", "organic flax", "organic quinoa"], avoids: ["synthetic dyes", "BHT", "artificial sweeteners"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Kroger", "Amazon"], priceRange: "mid", reason: "USDA Organic with no synthetic dyes, colors, or sweeteners." },
    { name: "One Degree Sprouted Oat O's", brand: "One Degree", score: 82, category: "cereal", subcategory: "puffs", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["sprouted oats", "cane sugar", "sea salt"], avoids: ["artificial colors", "BHT", "artificial sweeteners"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Sprouted oats with minimal sweetening and full ingredient traceability." },
    { name: "Ezekiel 4:9 Sprouted Cereal", brand: "Food For Life", score: 89, category: "cereal", subcategory: "flakes", fixes: ["Artificial Sweetener", "Preservative", "Ultra-Processed", "Added Sugar"], keyIngredients: ["sprouted wheat", "sprouted barley", "sprouted lentils"], avoids: ["artificial sweeteners", "sugar", "preservatives"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Sprouts", "Trader Joe's", "Amazon"], priceRange: "mid", reason: "Sprouted grains with no added sugar or artificial sweeteners." },
    { name: "Bob's Red Mill Muesli", brand: "Bob's Red Mill", score: 83, category: "cereal", subcategory: "granola", fixes: ["Artificial Dye", "Preservative", "Ultra-Processed"], keyIngredients: ["whole grain oats", "dried fruit", "seeds"], avoids: ["artificial colors", "preservatives", "corn syrup"], certifications: ["Non-GMO"], whereToFind: ["Target", "Kroger", "Amazon", "Walmart"], priceRange: "budget", reason: "Whole grain muesli with real dried fruit and no artificial additives." },
    { name: "Seven Sundays Grain-Free Cereal", brand: "Seven Sundays", score: 80, category: "cereal", subcategory: "granola", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["coconut", "sunflower seeds", "maple syrup"], avoids: ["seed oils", "artificial dyes", "corn syrup"], certifications: ["Paleo", "Gluten-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Grain-free granola with clean fats and no seed oils." },
    { name: "Purely Elizabeth Ancient Grain Granola", brand: "Purely Elizabeth", score: 81, category: "cereal", subcategory: "granola", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["oats", "coconut oil", "quinoa", "amaranth"], avoids: ["canola oil", "corn syrup", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Ancient grains with coconut oil instead of seed oils." },
    { name: "Cascadian Farm Organic Granola", brand: "Cascadian Farm", score: 78, category: "cereal", subcategory: "granola", fixes: ["Artificial Dye", "Preservative"], keyIngredients: ["whole grain oats", "sugar", "canola oil"], avoids: ["artificial dyes", "preservatives", "BHT"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger"], priceRange: "budget", reason: "USDA Organic granola with no synthetic colors or preservatives." },
    { name: "Thrive Market Organic Cereal", brand: "Thrive Market", score: 79, category: "cereal", subcategory: "flakes", fixes: ["Artificial Dye", "Ultra-Processed", "Preservative"], keyIngredients: ["organic rice", "organic cane sugar"], avoids: ["artificial colors", "BHT", "TBHQ"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Thrive Market"], priceRange: "mid", reason: "Organic cereal with clean ingredients at a member price." },
  ],
  crackers: [
    { name: "Simple Mills Almond Flour Crackers", brand: "Simple Mills", score: 84, category: "crackers", subcategory: "grain-free", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["almond flour", "sunflower seeds", "flax"], avoids: ["canola oil", "soybean oil", "artificial flavors"], certifications: ["Non-GMO", "Grain-Free", "Paleo"], whereToFind: ["Whole Foods", "Target", "Amazon", "Costco"], priceRange: "mid", reason: "Grain-free with clean ingredients and no seed oils.", imageUrl: "https://images.openfoodfacts.org/images/products/085/239/300/0125/front_en.3.400.jpg" },
    { name: "Mary's Gone Crackers", brand: "Mary's Gone", score: 81, category: "crackers", subcategory: "seed-based", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["brown rice", "flax seeds", "sesame seeds"], avoids: ["canola oil", "artificial colors", "wheat"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic whole grain, gluten-free, and no artificial additives." },
    { name: "Hu Kitchen Grain-Free Crackers", brand: "Hu Kitchen", score: 79, category: "crackers", subcategory: "grain-free", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["cassava flour", "olive oil", "seeds"], avoids: ["canola oil", "sugar", "soy"], certifications: ["Paleo", "Grain-Free", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Paleo-friendly with cassava flour and no seed oils.", imageUrl: "https://images.openfoodfacts.org/images/products/008/154/300/6934/front_en.3.400.jpg" },
    { name: "Jilz Gluten Free Crackerz", brand: "Jilz", score: 80, category: "crackers", subcategory: "seed-based", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["almonds", "seeds", "egg whites"], avoids: ["canola oil", "grains", "soy"], certifications: ["Gluten-Free", "Grain-Free", "Paleo"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Seed-and-nut-based crackers with no grains or seed oils." },
    { name: "Flackers Flax Seed Crackers", brand: "Flackers", score: 83, category: "crackers", subcategory: "seed-based", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["flax seeds", "apple cider vinegar", "sea salt"], avoids: ["oil", "wheat", "corn"], certifications: ["USDA Organic", "Gluten-Free", "Vegan", "Keto"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Raw flax crackers with no oil, grains, or artificial anything." },
    { name: "Crunchmaster Multi-Seed Crackers", brand: "Crunchmaster", score: 74, category: "crackers", subcategory: "seed-based", fixes: ["Ultra-Processed", "Artificial Dye"], keyIngredients: ["brown rice", "sesame seeds", "quinoa"], avoids: ["artificial colors", "wheat", "corn syrup"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Kroger"], priceRange: "budget", reason: "Multi-seed gluten-free crackers at an accessible price point." },
    { name: "Lark Ellen Farm Grain-Free Bites", brand: "Lark Ellen", score: 78, category: "crackers", subcategory: "grain-free", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["sprouted seeds", "coconut oil", "spices"], avoids: ["canola oil", "grains", "soy"], certifications: ["USDA Organic", "Paleo", "Vegan"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Sprouted seed bites made with coconut oil and no grains." },
    { name: "Way Better Sprouted Tortilla Chips", brand: "Way Better", score: 76, category: "crackers", subcategory: "rice", fixes: ["Ultra-Processed", "Artificial Dye"], keyIngredients: ["sprouted corn", "sprouted seeds", "sunflower oil"], avoids: ["artificial colors", "MSG", "corn syrup"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Sprouted grain crackers with no artificial colors or MSG." },
  ],
  bars: [
    { name: "RXBAR Chocolate Sea Salt", brand: "RXBAR", score: 86, category: "bars", subcategory: "protein", fixes: ["Seed Oil", "Artificial Sweetener", "Ultra-Processed"], keyIngredients: ["egg whites", "dates", "almonds", "cocoa"], avoids: ["canola oil", "sucralose", "soy protein isolate"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "mid", reason: "Egg whites, dates, nuts, and cocoa — no seed oils or fillers." },
    { name: "Larabar Apple Pie", brand: "Larabar", score: 88, category: "bars", subcategory: "fruit", fixes: ["Seed Oil", "Artificial Sweetener", "Ultra-Processed", "Added Sugar"], keyIngredients: ["dates", "almonds", "apples", "cinnamon"], avoids: ["oil", "sugar", "artificial sweeteners"], certifications: ["Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Target", "Walmart", "Kroger", "Amazon"], priceRange: "budget", reason: "Only dates, almonds, and apples with no oils added." },
    { name: "That's It Apple + Mango Bar", brand: "That's It", score: 91, category: "bars", subcategory: "fruit", fixes: ["Seed Oil", "Artificial Sweetener", "Ultra-Processed", "Preservative", "Added Sugar"], keyIngredients: ["apples", "mangoes"], avoids: ["oil", "sugar", "preservatives", "artificial anything"], certifications: ["Non-GMO", "Vegan", "Paleo", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "budget", reason: "Two ingredients: real fruit pressed into a bar, nothing else." },
    { name: "KIND Dark Chocolate Nuts & Sea Salt", brand: "KIND", score: 76, category: "bars", subcategory: "nut", fixes: ["Artificial Sweetener", "Artificial Dye"], keyIngredients: ["almonds", "dark chocolate", "sea salt"], avoids: ["artificial sweeteners", "artificial colors", "corn syrup"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "budget", reason: "Whole nuts with dark chocolate and no artificial sweeteners." },
    { name: "GoMacro MacroBar", brand: "GoMacro", score: 80, category: "bars", subcategory: "protein", fixes: ["Artificial Sweetener", "Seed Oil", "Ultra-Processed"], keyIngredients: ["brown rice protein", "almond butter", "brown rice syrup"], avoids: ["sucralose", "canola oil", "soy protein"], certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic plant-based bar sweetened with brown rice syrup, not sucralose." },
    { name: "Thunderbird Real Food Bar", brand: "Thunderbird", score: 84, category: "bars", subcategory: "nut", fixes: ["Seed Oil", "Artificial Sweetener", "Ultra-Processed", "Added Sugar"], keyIngredients: ["dates", "cashews", "cacao nibs"], avoids: ["oil", "sugar", "artificial sweeteners", "soy"], certifications: ["Paleo", "Vegan", "Gluten-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Whole food bar with no added sugar, oil, or artificial ingredients." },
    { name: "Perfect Bar Peanut Butter", brand: "Perfect Bar", score: 77, category: "bars", subcategory: "protein", fixes: ["Ultra-Processed", "Artificial Sweetener"], keyIngredients: ["peanut butter", "honey", "superfoods"], avoids: ["artificial sweeteners", "soy protein", "corn syrup"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Costco", "Amazon"], priceRange: "mid", reason: "Refrigerated bar with organic peanut butter and 20+ superfoods." },
    { name: "88 Acres Seed Bar", brand: "88 Acres", score: 82, category: "bars", subcategory: "snack", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["pumpkin seeds", "sunflower seeds", "maple syrup"], avoids: ["tree nuts", "canola oil", "artificial colors"], certifications: ["Non-GMO", "Vegan", "Gluten-Free"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Nut-free seed bar with clean ingredients and no artificial additives." },
  ],
  yogurt: [
    { name: "Siggi's Icelandic Yogurt", brand: "Siggi's", score: 88, category: "yogurt", subcategory: "icelandic", fixes: ["Added Sugar", "Artificial Sweetener", "Ultra-Processed"], keyIngredients: ["pasteurized skim milk", "live cultures"], avoids: ["artificial sweeteners", "corn syrup", "artificial flavors"], certifications: ["Non-GMO"], whereToFind: ["Target", "Whole Foods", "Kroger", "Walmart"], priceRange: "mid", reason: "Simple ingredients with high protein, low sugar, and no additives." },
    { name: "Fage Total Plain Greek Yogurt", brand: "Fage", score: 87, category: "yogurt", subcategory: "greek", fixes: ["Added Sugar", "Artificial Sweetener", "Ultra-Processed", "Emulsifier"], keyIngredients: ["milk", "live cultures"], avoids: ["sugar", "artificial sweeteners", "thickeners"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger", "Costco"], priceRange: "budget", reason: "Only milk and live cultures — zero additives or preservatives." },
    { name: "Stonyfield Organic Whole Milk Yogurt", brand: "Stonyfield", score: 85, category: "yogurt", subcategory: "regular", fixes: ["Artificial Dye", "Artificial Sweetener", "Preservative"], keyIngredients: ["organic whole milk", "live cultures"], avoids: ["artificial flavors", "artificial colors", "synthetic hormones"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Whole Foods", "Kroger", "Walmart"], priceRange: "mid", reason: "USDA Organic with no artificial flavors, colors, or sweeteners." },
    { name: "Coconut Cult Probiotic Coconut Yogurt", brand: "Coconut Cult", score: 81, category: "yogurt", subcategory: "coconut", fixes: ["Added Sugar", "Artificial Sweetener", "Emulsifier"], keyIngredients: ["coconut cream", "probiotics"], avoids: ["sugar", "gums", "artificial sweeteners"], certifications: ["Vegan", "Paleo", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Living probiotic coconut yogurt with no sugar or gums." },
    { name: "Lavva Plant-Based Yogurt", brand: "Lavva", score: 79, category: "yogurt", subcategory: "coconut", fixes: ["Added Sugar", "Artificial Sweetener", "Emulsifier", "Ultra-Processed"], keyIngredients: ["plantains", "coconut cream", "cassava"], avoids: ["sugar", "gums", "artificial sweeteners"], certifications: ["Vegan", "Paleo", "Gluten-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts"], priceRange: "premium", reason: "Whole-food plant-based yogurt with no added sugar or gums." },
    { name: "Forager Project Cashewmilk Yogurt", brand: "Forager", score: 77, category: "yogurt", subcategory: "coconut", fixes: ["Artificial Sweetener", "Artificial Dye"], keyIngredients: ["organic cashew milk", "live cultures", "tapioca"], avoids: ["artificial sweeteners", "artificial colors", "soy"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Sprouts"], priceRange: "mid", reason: "Organic cashew yogurt with live cultures and no artificial additives." },
    { name: "Two Good Low Fat Greek Yogurt", brand: "Two Good", score: 74, category: "yogurt", subcategory: "greek", fixes: ["Added Sugar"], keyIngredients: ["ultra-filtered milk", "live cultures", "stevia"], avoids: ["high sugar", "corn syrup", "artificial colors"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger"], priceRange: "budget", reason: "Only 2g of sugar per cup through slow-straining, not artificial sweeteners." },
    { name: "Nancy's Organic Whole Milk Yogurt", brand: "Nancy's", score: 83, category: "yogurt", subcategory: "regular", fixes: ["Artificial Dye", "Preservative", "Ultra-Processed"], keyIngredients: ["organic whole milk", "live cultures"], avoids: ["artificial colors", "preservatives", "thickeners"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Organic with billions of live probiotics and no thickeners." },
  ],
  cookies: [
    { name: "Hu Kitchen Chocolate Chip Cookies", brand: "Hu Kitchen", score: 77, category: "cookies", subcategory: "grain-free", fixes: ["Seed Oil", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["cassava flour", "coconut sugar", "cacao"], avoids: ["canola oil", "refined sugar", "artificial flavors"], certifications: ["Paleo", "Grain-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "No refined sugar, seed oils, or artificial flavors." },
    { name: "Simple Mills Crunchy Cookies", brand: "Simple Mills", score: 79, category: "cookies", subcategory: "grain-free", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["almond flour", "coconut oil", "coconut sugar"], avoids: ["canola oil", "soybean oil", "corn syrup"], certifications: ["Non-GMO", "Grain-Free", "Paleo"], whereToFind: ["Whole Foods", "Target", "Amazon", "Costco"], priceRange: "mid", reason: "Almond flour base with coconut oil instead of seed oils." },
    { name: "Partake Crunchy Cookies", brand: "Partake", score: 75, category: "cookies", subcategory: "grain-free", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["cassava flour", "sunflower butter", "cane sugar"], avoids: ["artificial colors", "top 8 allergens", "preservatives"], certifications: ["Non-GMO", "Vegan", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Allergy-friendly with clean ingredients and no artificial additives." },
    { name: "Lenny & Larry's Complete Cookie", brand: "Lenny & Larry's", score: 68, category: "cookies", subcategory: "protein", fixes: ["Artificial Dye"], keyIngredients: ["pea protein", "wheat flour", "cane sugar"], avoids: ["artificial colors", "high-fructose corn syrup"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Target", "Walmart", "Amazon", "GNC"], priceRange: "budget", reason: "High-protein vegan cookie with no artificial colors or HFCS." },
    { name: "Emmy's Organic Coconut Cookies", brand: "Emmy's", score: 80, category: "cookies", subcategory: "grain-free", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["coconut", "almond flour", "maple syrup"], avoids: ["canola oil", "refined sugar", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Raw organic coconut cookies with no baking and no seed oils." },
    { name: "Maxine's Heavenly Cookies", brand: "Maxine's Heavenly", score: 76, category: "cookies", subcategory: "chocolate", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["oat flour", "coconut oil", "dark chocolate"], avoids: ["canola oil", "refined sugar", "artificial sweeteners"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Soft-baked with coconut oil and dark chocolate, no seed oils." },
    { name: "Oat Haus Granola Butter Cookies", brand: "Oat Haus", score: 74, category: "cookies", subcategory: "oat", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["oats", "sunflower oil", "maple syrup"], avoids: ["canola oil", "artificial flavors", "corn syrup"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Made with granola butter and no artificial ingredients." },
    { name: "Micky's Coconut Macaroons", brand: "Micky's", score: 78, category: "cookies", subcategory: "grain-free", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["coconut", "egg whites", "vanilla"], avoids: ["oil", "artificial colors", "preservatives"], certifications: ["Paleo", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts"], priceRange: "mid", reason: "Simple coconut macaroons with no oil or artificial additives." },
  ],
  "peanut butter": [
    { name: "Once Again Organic Peanut Butter", brand: "Once Again", score: 89, category: "peanut butter", subcategory: "natural", fixes: ["Seed Oil", "Added Sugar", "Ultra-Processed"], keyIngredients: ["dry-roasted organic peanuts", "salt"], avoids: ["palm oil", "sugar", "hydrogenated oils"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Just dry-roasted organic peanuts and salt — no palm or seed oils." },
    { name: "Teddie All Natural Peanut Butter", brand: "Teddie", score: 86, category: "peanut butter", subcategory: "natural", fixes: ["Seed Oil", "Added Sugar", "Ultra-Processed"], keyIngredients: ["peanuts", "salt"], avoids: ["palm oil", "sugar", "hydrogenated oils"], certifications: ["Non-GMO"], whereToFind: ["Walmart", "Amazon", "Stop & Shop"], priceRange: "budget", reason: "Only peanuts and salt, no hydrogenated oils or added sugar." },
    { name: "Santa Cruz Organic Peanut Butter", brand: "Santa Cruz", score: 84, category: "peanut butter", subcategory: "natural", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic roasted peanuts"], avoids: ["palm oil", "sugar", "seed oils"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "USDA Organic with only roasted peanuts — zero seed oils." },
    { name: "Wild Friends Classic Peanut Butter", brand: "Wild Friends", score: 82, category: "peanut butter", subcategory: "natural", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["peanuts", "palm fruit oil", "sea salt"], avoids: ["hydrogenated oils", "corn syrup", "artificial flavors"], certifications: ["Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Minimal ingredients with no hydrogenated oils or artificial flavors." },
    { name: "Spread the Love Naked Peanut Butter", brand: "Spread the Love", score: 88, category: "peanut butter", subcategory: "natural", fixes: ["Seed Oil", "Added Sugar", "Ultra-Processed"], keyIngredients: ["dry-roasted peanuts"], avoids: ["oil", "sugar", "salt"], certifications: ["Non-GMO", "Vegan", "Gluten-Free"], whereToFind: ["Amazon", "Whole Foods"], priceRange: "mid", reason: "Single ingredient: dry-roasted peanuts. Nothing else." },
    { name: "365 Organic Creamy Peanut Butter", brand: "365", score: 81, category: "peanut butter", subcategory: "natural", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic peanuts", "salt"], avoids: ["palm oil", "sugar", "hydrogenated oils"], certifications: ["USDA Organic"], whereToFind: ["Whole Foods"], priceRange: "budget", reason: "Whole Foods store brand organic — affordable and clean." },
    { name: "Barney Almond Butter", brand: "Barney", score: 85, category: "peanut butter", subcategory: "almond", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["blanched almonds"], avoids: ["palm oil", "sugar", "seed oils"], certifications: ["Non-GMO", "Gluten-Free", "Paleo"], whereToFind: ["Target", "Whole Foods", "Amazon"], priceRange: "mid", reason: "Smooth blanched almond butter with nothing added." },
    { name: "SunButter Organic Sunflower Butter", brand: "SunButter", score: 80, category: "peanut butter", subcategory: "sunflower", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic sunflower seeds", "sugar", "salt"], avoids: ["peanuts", "tree nuts", "hydrogenated oils"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Whole Foods", "Amazon", "Walmart"], priceRange: "mid", reason: "Nut-free alternative with organic sunflower seeds." },
  ],
  bread: [
    { name: "Ezekiel 4:9 Sprouted Bread", brand: "Food For Life", score: 89, category: "bread", subcategory: "sprouted", fixes: ["Preservative", "Added Sugar", "Ultra-Processed"], keyIngredients: ["sprouted wheat", "sprouted barley", "sprouted lentils"], avoids: ["sugar", "preservatives", "enriched flour"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Trader Joe's", "Sprouts"], priceRange: "mid", reason: "Sprouted whole grains with no preservatives or added sugar." },
    { name: "Dave's Killer Bread Thin-Sliced", brand: "Dave's Killer Bread", score: 79, category: "bread", subcategory: "sprouted", fixes: ["Preservative", "Artificial Dye"], keyIngredients: ["organic whole wheat", "seeds", "organic cane sugar"], avoids: ["artificial preservatives", "artificial colors", "HFCS"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Walmart", "Costco", "Kroger"], priceRange: "mid", reason: "USDA Organic whole grains with no artificial preservatives." },
    { name: "Base Culture Keto Bread", brand: "Base Culture", score: 77, category: "bread", subcategory: "grain-free", fixes: ["Ultra-Processed", "Added Sugar", "Seed Oil"], keyIngredients: ["almond flour", "coconut flour", "eggs"], avoids: ["grains", "sugar", "seed oils"], certifications: ["Paleo", "Gluten-Free", "Grain-Free", "Keto"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Grain-free and gluten-free with almond and coconut flour." },
    { name: "Carbonaut Low Carb Bread", brand: "Carbonaut", score: 74, category: "bread", subcategory: "gluten-free", fixes: ["Added Sugar", "Ultra-Processed"], keyIngredients: ["wheat protein", "oat fiber", "flax"], avoids: ["sugar", "corn syrup", "artificial colors"], certifications: ["Keto", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Low-carb with no added sugar and high fiber." },
    { name: "Canyon Bakehouse Gluten-Free Bread", brand: "Canyon Bakehouse", score: 76, category: "bread", subcategory: "gluten-free", fixes: ["Ultra-Processed"], keyIngredients: ["whole grain brown rice flour", "tapioca starch", "eggs"], avoids: ["gluten", "artificial colors", "HFCS"], certifications: ["Gluten-Free", "Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger", "Amazon"], priceRange: "mid", reason: "Whole grain gluten-free bread with no artificial additives." },
    { name: "Alvarado Street Sprouted Wheat Bread", brand: "Alvarado Street", score: 82, category: "bread", subcategory: "sprouted", fixes: ["Preservative", "Ultra-Processed", "Added Sugar"], keyIngredients: ["sprouted wheat berries", "honey", "yeast"], avoids: ["preservatives", "enriched flour", "corn syrup"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts"], priceRange: "mid", reason: "Organic sprouted wheat with minimal natural sweetening." },
    { name: "Silver Hills Sprouted Bread", brand: "Silver Hills", score: 80, category: "bread", subcategory: "sprouted", fixes: ["Preservative", "Ultra-Processed"], keyIngredients: ["sprouted wheat", "sprouted rye", "oat bran"], avoids: ["preservatives", "enriched flour", "sugar"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Organic sprouted grain with no sugar or preservatives." },
    { name: "SRSLY Sourdough Bread", brand: "SRSLY", score: 78, category: "bread", subcategory: "sourdough", fixes: ["Ultra-Processed", "Preservative"], keyIngredients: ["tapioca starch", "sourdough culture", "eggs"], avoids: ["gluten", "preservatives", "gums"], certifications: ["Gluten-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Gluten-free sourdough made with traditional fermentation." },
  ],
  pasta: [
    { name: "Banza Chickpea Pasta", brand: "Banza", score: 84, category: "pasta", subcategory: "legume", fixes: ["Ultra-Processed"], keyIngredients: ["chickpea flour", "tapioca", "pea protein"], avoids: ["enriched flour", "artificial colors"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Whole Foods", "Amazon"], priceRange: "mid", reason: "High protein chickpea pasta with no artificial ingredients." },
    { name: "Jovial Organic Brown Rice Pasta", brand: "Jovial", score: 88, category: "pasta", subcategory: "rice", fixes: ["Ultra-Processed", "Preservative"], keyIngredients: ["organic brown rice"], avoids: ["additives", "corn", "wheat"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Single ingredient organic brown rice — gluten-free with no additives." },
    { name: "Tolerant Red Lentil Pasta", brand: "Tolerant", score: 86, category: "pasta", subcategory: "legume", fixes: ["Ultra-Processed"], keyIngredients: ["organic red lentil flour"], avoids: ["wheat", "additives", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Single-ingredient organic red lentil pasta with 25g protein per serving." },
    { name: "Explore Cuisine Edamame Spaghetti", brand: "Explore Cuisine", score: 83, category: "pasta", subcategory: "legume", fixes: ["Ultra-Processed"], keyIngredients: ["organic edamame flour"], avoids: ["wheat", "additives", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic edamame spaghetti with 24g protein per serving." },
    { name: "Tinkyada Brown Rice Pasta", brand: "Tinkyada", score: 82, category: "pasta", subcategory: "rice", fixes: ["Ultra-Processed"], keyIngredients: ["brown rice", "rice bran"], avoids: ["wheat", "corn", "additives"], certifications: ["Gluten-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "budget", reason: "Rice pasta with great texture and no additives." },
    { name: "Cappello's Almond Flour Pasta", brand: "Cappello's", score: 80, category: "pasta", subcategory: "grain-free", fixes: ["Ultra-Processed", "Seed Oil"], keyIngredients: ["almond flour", "tapioca flour", "eggs"], avoids: ["grains", "seed oils", "preservatives"], certifications: ["Paleo", "Grain-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Grain-free almond flour pasta with no seed oils." },
    { name: "Jovial Einkorn Pasta", brand: "Jovial", score: 85, category: "pasta", subcategory: "sprouted", fixes: ["Ultra-Processed", "Preservative"], keyIngredients: ["organic einkorn wheat"], avoids: ["modern wheat", "preservatives", "additives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Ancient einkorn wheat — easier to digest than modern wheat." },
    { name: "Ancient Harvest Quinoa Pasta", brand: "Ancient Harvest", score: 79, category: "pasta", subcategory: "legume", fixes: ["Ultra-Processed"], keyIngredients: ["organic quinoa flour", "organic corn flour"], avoids: ["wheat", "additives", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Amazon"], priceRange: "budget", reason: "Quinoa-based pasta with clean ingredients at an affordable price." },
  ],
  "salad dressing": [
    { name: "Primal Kitchen Caesar Dressing", brand: "Primal Kitchen", score: 84, category: "salad dressing", subcategory: "oil-based", fixes: ["Seed Oil", "Ultra-Processed", "Preservative"], keyIngredients: ["avocado oil", "organic lemon juice", "organic vinegar"], avoids: ["canola oil", "soybean oil", "sugar"], certifications: ["Paleo", "Keto", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon", "Costco"], priceRange: "mid", reason: "Made with avocado oil instead of canola or soybean oil." },
    { name: "Tessemae's Organic Ranch", brand: "Tessemae's", score: 81, category: "salad dressing", subcategory: "creamy", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic sunflower oil", "organic buttermilk", "organic herbs"], avoids: ["canola oil", "sugar", "artificial preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic oil base with no canola oil or sugar." },
    { name: "Bragg Organic Vinaigrette", brand: "Bragg", score: 80, category: "salad dressing", subcategory: "oil-based", fixes: ["Seed Oil", "Ultra-Processed", "Preservative"], keyIngredients: ["organic olive oil", "organic apple cider vinegar"], avoids: ["canola oil", "preservatives", "corn syrup"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Walmart", "Amazon"], priceRange: "budget", reason: "Olive oil and apple cider vinegar base with no seed oils." },
    { name: "Thrive Market Organic Ranch", brand: "Thrive Market", score: 78, category: "salad dressing", subcategory: "creamy", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil", "organic buttermilk", "herbs"], avoids: ["canola oil", "MSG", "artificial colors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Thrive Market"], priceRange: "mid", reason: "Avocado oil ranch with organic ingredients." },
    { name: "Chosen Foods Avocado Oil Dressing", brand: "Chosen Foods", score: 82, category: "salad dressing", subcategory: "oil-based", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil", "organic vinegar", "herbs"], avoids: ["canola oil", "soybean oil", "corn syrup"], certifications: ["Non-GMO", "Keto"], whereToFind: ["Costco", "Target", "Amazon"], priceRange: "mid", reason: "Avocado oil base with no seed oils — available at Costco." },
    { name: "Noble Made Classic Marinade", brand: "Noble Made", score: 79, category: "salad dressing", subcategory: "oil-based", fixes: ["Seed Oil", "Ultra-Processed", "Added Sugar"], keyIngredients: ["avocado oil", "coconut aminos", "vinegar"], avoids: ["canola oil", "sugar", "soy sauce"], certifications: ["Paleo", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Avocado oil marinade with coconut aminos instead of soy." },
    { name: "Otamot Organic Tomato Dressing", brand: "Otamot", score: 77, category: "salad dressing", subcategory: "creamy", fixes: ["Seed Oil", "Ultra-Processed", "Preservative"], keyIngredients: ["organic tomatoes", "organic butternut squash", "organic olive oil"], avoids: ["canola oil", "preservatives", "sugar"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Veggie-loaded dressing with no seed oils or preservatives." },
    { name: "Cibo Naturals Pesto", brand: "Cibo", score: 76, category: "salad dressing", subcategory: "oil-based", fixes: ["Seed Oil"], keyIngredients: ["olive oil", "basil", "parmesan"], avoids: ["canola oil", "artificial flavors"], certifications: ["Non-GMO"], whereToFind: ["Costco", "Amazon"], priceRange: "mid", reason: "Olive oil pesto that works as a dressing — no seed oils." },
  ],
  sauce: [
    { name: "Primal Kitchen Ketchup", brand: "Primal Kitchen", score: 84, category: "sauce", subcategory: "ketchup", fixes: ["Added Sugar", "Ultra-Processed", "Preservative"], keyIngredients: ["organic tomatoes", "organic dates", "organic vinegar"], avoids: ["HFCS", "corn syrup", "preservatives"], certifications: ["USDA Organic", "Paleo", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon", "Costco"], priceRange: "mid", reason: "Sweetened with dates with no high-fructose corn syrup or seed oils." },
    { name: "Sir Kensington's Classic Ketchup", brand: "Sir Kensington's", score: 81, category: "sauce", subcategory: "ketchup", fixes: ["Added Sugar", "Ultra-Processed"], keyIngredients: ["tomatoes", "cane sugar", "vinegar"], avoids: ["HFCS", "artificial preservatives", "artificial colors"], certifications: ["Non-GMO"], whereToFind: ["Target", "Whole Foods", "Amazon"], priceRange: "mid", reason: "Non-GMO tomatoes with no artificial preservatives." },
    { name: "Chosen Foods Avocado Oil Mayo", brand: "Chosen Foods", score: 83, category: "sauce", subcategory: "mayo", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil", "cage-free eggs", "vinegar"], avoids: ["canola oil", "soybean oil", "sugar"], certifications: ["Non-GMO", "Keto", "Paleo"], whereToFind: ["Costco", "Target", "Amazon"], priceRange: "mid", reason: "Avocado oil mayo with cage-free eggs and no seed oils." },
    { name: "Tessemae's Organic Ketchup", brand: "Tessemae's", score: 80, category: "sauce", subcategory: "ketchup", fixes: ["Added Sugar", "Ultra-Processed"], keyIngredients: ["organic tomato paste", "organic dates", "vinegar"], avoids: ["sugar", "corn syrup", "artificial colors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic ketchup sweetened with dates, not sugar or HFCS." },
    { name: "New Primal Classic BBQ Sauce", brand: "New Primal", score: 78, category: "sauce", subcategory: "bbq", fixes: ["Added Sugar", "Ultra-Processed", "Seed Oil"], keyIngredients: ["organic tomato paste", "coconut aminos", "dates"], avoids: ["sugar", "canola oil", "soy"], certifications: ["Paleo", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "BBQ sauce with no added sugar, seed oils, or soy." },
    { name: "Noble Made Classic Buffalo Sauce", brand: "Noble Made", score: 79, category: "sauce", subcategory: "hot sauce", fixes: ["Seed Oil", "Ultra-Processed", "Preservative"], keyIngredients: ["cayenne peppers", "coconut oil", "vinegar"], avoids: ["canola oil", "preservatives", "artificial flavors"], certifications: ["Paleo", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Buffalo sauce made with coconut oil instead of seed oils." },
    { name: "Rao's Homemade Marinara", brand: "Rao's", score: 85, category: "sauce", subcategory: "pasta", fixes: ["Added Sugar", "Seed Oil", "Ultra-Processed"], keyIngredients: ["Italian tomatoes", "olive oil", "garlic", "basil"], avoids: ["sugar", "canola oil", "preservatives"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "mid", reason: "Italian tomatoes and olive oil — no added sugar or seed oils." },
    { name: "Otamot Essential Sauce", brand: "Otamot", score: 82, category: "sauce", subcategory: "pasta", fixes: ["Added Sugar", "Ultra-Processed"], keyIngredients: ["organic tomatoes", "organic sweet potatoes", "organic carrots"], avoids: ["sugar", "preservatives", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "10 organic veggies blended into a pasta sauce with no sugar." },
  ],
  milk: [
    { name: "Malk Unsweetened Almond Milk", brand: "Malk", score: 89, category: "milk", subcategory: "almond", fixes: ["Emulsifier", "Ultra-Processed", "Preservative"], keyIngredients: ["filtered water", "organic almonds", "sea salt"], avoids: ["gums", "carrageenan", "oils"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Target"], priceRange: "premium", reason: "Only filtered water, almonds, and salt — no gums or oils." },
    { name: "Three Trees Organic Almond Milk", brand: "Three Trees", score: 87, category: "milk", subcategory: "almond", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["filtered water", "organic almonds"], avoids: ["gums", "carrageenan", "preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Clean label with no carrageenan, gums, or preservatives." },
    { name: "Califia Farms Unsweetened Oat Milk", brand: "Califia Farms", score: 77, category: "milk", subcategory: "oat", fixes: ["Artificial Dye", "Artificial Sweetener"], keyIngredients: ["oat milk", "calcium", "vitamins"], avoids: ["artificial flavors", "HFCS", "carrageenan"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Target", "Walmart", "Kroger", "Amazon"], priceRange: "mid", reason: "No artificial flavors or high-fructose sweeteners." },
    { name: "MOOALA Organic Almondmilk", brand: "MOOALA", score: 82, category: "milk", subcategory: "almond", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["organic almonds", "organic coconut cream", "himalayan salt"], avoids: ["gums", "carrageenan", "soy lecithin"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Organic almond milk with coconut cream and no gums." },
    { name: "Elmhurst 1925 Oat Milk", brand: "Elmhurst", score: 84, category: "milk", subcategory: "oat", fixes: ["Emulsifier", "Ultra-Processed", "Seed Oil"], keyIngredients: ["filtered water", "whole grain oats"], avoids: ["gums", "oils", "emulsifiers"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "No gums, oils, or emulsifiers — just oats and water." },
    { name: "Oatly Full Fat Oat Milk", brand: "Oatly", score: 75, category: "milk", subcategory: "oat", fixes: ["Artificial Dye", "Artificial Sweetener"], keyIngredients: ["oats", "rapeseed oil", "calcium"], avoids: ["artificial sweeteners", "corn syrup", "artificial colors"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Target", "Walmart", "Kroger", "Amazon"], priceRange: "mid", reason: "Full-fat oat milk with creamy texture and no artificial additives." },
    { name: "Forager Project Cashewmilk", brand: "Forager", score: 80, category: "milk", subcategory: "cashew", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["organic cashews", "filtered water", "organic coconut cream"], avoids: ["gums", "carrageenan", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Sprouts"], priceRange: "mid", reason: "Organic cashew milk with coconut cream and no gums." },
    { name: "So Delicious Organic Coconut Milk", brand: "So Delicious", score: 76, category: "milk", subcategory: "coconut", fixes: ["Artificial Sweetener", "Artificial Dye"], keyIngredients: ["organic coconut cream", "filtered water", "vitamins"], avoids: ["artificial sweeteners", "artificial colors", "HFCS"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Target", "Walmart", "Whole Foods"], priceRange: "mid", reason: "Organic coconut milk with no artificial sweeteners or colors." },
  ],
  soda: [
    { name: "Olipop Vintage Cola", brand: "Olipop", score: 78, category: "soda", subcategory: "prebiotic", fixes: ["Added Sugar", "Artificial Sweetener", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["chicory root fiber", "cassava syrup", "natural flavors"], avoids: ["HFCS", "artificial sweeteners", "artificial colors"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Target", "Whole Foods", "Amazon", "Costco"], priceRange: "mid", reason: "Prebiotic soda with natural sweeteners and no artificial dyes." },
    { name: "Poppi Prebiotic Soda", brand: "Poppi", score: 75, category: "soda", subcategory: "prebiotic", fixes: ["Added Sugar", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["apple cider vinegar", "cane sugar", "fruit juice"], avoids: ["artificial colors", "HFCS", "artificial sweeteners"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Target", "Walmart", "Amazon", "Costco"], priceRange: "mid", reason: "Apple cider vinegar based with natural fruit flavors." },
    { name: "Zevia Zero Calorie Soda", brand: "Zevia", score: 72, category: "soda", subcategory: "stevia", fixes: ["Added Sugar", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["stevia", "carbonated water", "natural flavors"], avoids: ["sugar", "artificial colors", "artificial sweeteners"], certifications: ["Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Target", "Walmart", "Amazon", "Kroger"], priceRange: "budget", reason: "Sweetened with stevia instead of sugar or artificial sweeteners." },
    { name: "Humm Kombucha", brand: "Humm", score: 74, category: "soda", subcategory: "kombucha", fixes: ["Artificial Sweetener", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic tea", "organic sugar", "live cultures"], avoids: ["artificial sweeteners", "artificial colors", "preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Whole Foods", "Walmart"], priceRange: "mid", reason: "Organic kombucha with live cultures and no artificial additives." },
    { name: "Health-Ade Kombucha", brand: "Health-Ade", score: 76, category: "soda", subcategory: "kombucha", fixes: ["Artificial Sweetener", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["cold-pressed juice", "organic tea", "live cultures"], avoids: ["artificial sweeteners", "artificial colors", "preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Sprouts", "Amazon"], priceRange: "mid", reason: "Cold-pressed organic kombucha brewed in small batches." },
    { name: "Kevita Sparkling Probiotic", brand: "Kevita", score: 73, category: "soda", subcategory: "kombucha", fixes: ["Artificial Sweetener", "Artificial Dye"], keyIngredients: ["organic tea", "organic stevia", "live probiotics"], avoids: ["artificial sweeteners", "artificial colors", "corn syrup"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger"], priceRange: "budget", reason: "Organic probiotic drink with stevia and live cultures." },
    { name: "Culture Pop Sparkling Probiotic", brand: "Culture Pop", score: 77, category: "soda", subcategory: "prebiotic", fixes: ["Added Sugar", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic fruit juice", "live cultures", "organic cane sugar"], avoids: ["artificial colors", "HFCS", "artificial sweeteners"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Organic sparkling probiotic with real fruit juice." },
    { name: "Spindrift Sparkling Water", brand: "Spindrift", score: 82, category: "soda", subcategory: "sparkling water", fixes: ["Added Sugar", "Artificial Sweetener", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["sparkling water", "real squeezed fruit"], avoids: ["sugar", "artificial sweeteners", "natural flavors"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Amazon", "Costco"], priceRange: "budget", reason: "Just sparkling water and real squeezed fruit — no sweeteners." },
  ],
  "energy drinks": [
    { name: "Guayakí Yerba Mate", brand: "Guayakí", score: 82, category: "energy drinks", subcategory: "natural caffeine", fixes: ["Artificial Sweetener", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic yerba mate", "organic cane sugar"], avoids: ["artificial sweeteners", "artificial colors", "taurine"], certifications: ["USDA Organic", "Non-GMO", "Fair Trade"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic yerba mate with natural caffeine and no artificial additives." },
    { name: "Hiball Organic Energy Water", brand: "Hiball", score: 79, category: "energy drinks", subcategory: "natural caffeine", fixes: ["Artificial Sweetener", "Artificial Dye", "Added Sugar", "Ultra-Processed"], keyIngredients: ["organic caffeine", "organic guarana", "sparkling water"], avoids: ["artificial sweeteners", "sugar", "artificial colors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Whole Foods", "Amazon"], priceRange: "mid", reason: "USDA Organic sparkling energy with zero sugar and no dyes." },
    { name: "RUNA Clean Energy", brand: "RUNA", score: 80, category: "energy drinks", subcategory: "natural caffeine", fixes: ["Artificial Dye", "Artificial Sweetener", "Ultra-Processed"], keyIngredients: ["organic guayusa", "organic cane sugar"], avoids: ["artificial dyes", "artificial sweeteners", "taurine"], certifications: ["USDA Organic", "Non-GMO", "Fair Trade"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Brewed from guayusa leaves with no artificial dyes or flavors." },
    { name: "Matchabar Hustle Matcha Energy", brand: "Matchabar", score: 77, category: "energy drinks", subcategory: "natural caffeine", fixes: ["Artificial Dye", "Artificial Sweetener"], keyIngredients: ["ceremonial matcha", "coconut water", "lemon juice"], avoids: ["synthetic dyes", "artificial sweeteners", "taurine"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Matcha-based energy with natural color and no synthetic dyes." },
    { name: "Ryze Mushroom Coffee", brand: "Ryze", score: 76, category: "energy drinks", subcategory: "adaptogen", fixes: ["Artificial Sweetener", "Ultra-Processed"], keyIngredients: ["organic mushroom blend", "organic coffee", "MCT oil"], avoids: ["artificial sweeteners", "sugar", "artificial flavors"], certifications: ["USDA Organic"], whereToFind: ["Amazon", "ryze.com"], priceRange: "premium", reason: "Mushroom coffee blend with adaptogens and no artificial sweeteners." },
    { name: "Four Sigmatic Mushroom Coffee", brand: "Four Sigmatic", score: 75, category: "energy drinks", subcategory: "adaptogen", fixes: ["Artificial Sweetener", "Ultra-Processed"], keyIngredients: ["organic coffee", "lion's mane", "chaga"], avoids: ["artificial sweeteners", "sugar", "fillers"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Functional mushroom coffee with lion's mane and no fillers." },
    { name: "Odyssey Elixir", brand: "Odyssey", score: 74, category: "energy drinks", subcategory: "adaptogen", fixes: ["Artificial Sweetener", "Artificial Dye"], keyIngredients: ["lion's mane", "cordyceps", "green tea caffeine"], avoids: ["artificial sweeteners", "artificial colors", "sugar"], certifications: ["Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Functional mushroom elixir with natural caffeine from green tea." },
    { name: "Sunwink Sparkling Herbal Tonic", brand: "Sunwink", score: 78, category: "energy drinks", subcategory: "adaptogen", fixes: ["Artificial Sweetener", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic lemon balm", "organic ashwagandha", "sparkling water"], avoids: ["artificial sweeteners", "artificial colors", "caffeine"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic herbal tonic with adaptogens and no artificial anything." },
  ],
  "frozen meals": [
    { name: "Amy's Organic Mexican Casserole", brand: "Amy's Kitchen", score: 76, category: "frozen meals", subcategory: "bowls", fixes: ["Seed Oil", "Preservative", "Ultra-Processed"], keyIngredients: ["organic beans", "organic rice", "organic cheese"], avoids: ["canola oil", "preservatives", "MSG"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Kroger"], priceRange: "mid", reason: "Made with organic ingredients and no seed oils or preservatives." },
    { name: "Primal Kitchen Frozen Bowl", brand: "Primal Kitchen", score: 78, category: "frozen meals", subcategory: "bowls", fixes: ["Seed Oil", "Ultra-Processed", "Preservative"], keyIngredients: ["avocado oil", "chicken", "vegetables"], avoids: ["canola oil", "soybean oil", "preservatives"], certifications: ["Paleo", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Paleo-friendly with avocado oil and no seed oils." },
    { name: "Daily Harvest Flatbread", brand: "Daily Harvest", score: 81, category: "frozen meals", subcategory: "pizza", fixes: ["Preservative", "Ultra-Processed", "Seed Oil"], keyIngredients: ["sweet potato crust", "organic vegetables", "cashew cream"], avoids: ["preservatives", "seed oils", "artificial flavors"], certifications: ["Vegan", "Gluten-Free", "Non-GMO"], whereToFind: ["Daily Harvest (delivery)"], priceRange: "premium", reason: "Plant-based with no preservatives, just whole frozen vegetables." },
    { name: "Tattooed Chef Plant-Based Bowl", brand: "Tattooed Chef", score: 74, category: "frozen meals", subcategory: "bowls", fixes: ["Preservative", "Artificial Dye"], keyIngredients: ["cauliflower rice", "organic vegetables", "plant protein"], avoids: ["preservatives", "artificial colors", "MSG"], certifications: ["Vegan", "Non-GMO"], whereToFind: ["Target", "Walmart", "Costco"], priceRange: "budget", reason: "Simple plant ingredients with no synthetic preservatives." },
    { name: "Strong Roots Mixed Root Fries", brand: "Strong Roots", score: 77, category: "frozen meals", subcategory: "entrees", fixes: ["Seed Oil", "Ultra-Processed", "Preservative"], keyIngredients: ["sweet potatoes", "parsnips", "sunflower oil"], avoids: ["canola oil", "preservatives", "artificial flavors"], certifications: ["Vegan", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Walmart"], priceRange: "mid", reason: "Real root vegetables with sunflower oil and no preservatives." },
    { name: "Luvo Performance Kitchen Bowl", brand: "Luvo", score: 75, category: "frozen meals", subcategory: "bowls", fixes: ["Preservative", "Ultra-Processed"], keyIngredients: ["whole grains", "vegetables", "lean protein"], avoids: ["preservatives", "artificial colors", "MSG"], certifications: ["Non-GMO"], whereToFind: ["Target", "Whole Foods"], priceRange: "mid", reason: "Clean frozen bowls with whole grains and no preservatives." },
    { name: "Evol Lean & Fit Burrito", brand: "Evol", score: 72, category: "frozen meals", subcategory: "burritos", fixes: ["Preservative", "Artificial Dye"], keyIngredients: ["chicken", "beans", "brown rice"], avoids: ["artificial preservatives", "artificial colors", "HFCS"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger"], priceRange: "budget", reason: "Clean frozen burrito with no artificial preservatives or dyes." },
    { name: "Kevin's Natural Foods Thai Basil Chicken", brand: "Kevin's Natural", score: 79, category: "frozen meals", subcategory: "entrees", fixes: ["Seed Oil", "Ultra-Processed", "Preservative"], keyIngredients: ["chicken", "coconut aminos", "Thai basil"], avoids: ["canola oil", "soy sauce", "preservatives"], certifications: ["Paleo", "Non-GMO", "Gluten-Free"], whereToFind: ["Costco", "Target", "Whole Foods"], priceRange: "mid", reason: "Paleo Thai chicken with coconut aminos instead of soy." },
  ],
  chocolate: [
    { name: "Hu Simple Dark Chocolate", brand: "Hu Kitchen", score: 87, category: "chocolate", subcategory: "dark", fixes: ["Emulsifier", "Seed Oil", "Ultra-Processed"], keyIngredients: ["organic cacao", "coconut sugar"], avoids: ["soy lecithin", "seed oils", "refined sugar"], certifications: ["Paleo", "Vegan", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Simple cacao and coconut sugar with no soy lecithin or seed oils." },
    { name: "Alter Eco Dark Chocolate", brand: "Alter Eco", score: 84, category: "chocolate", subcategory: "dark", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["organic cacao", "organic cane sugar", "organic cocoa butter"], avoids: ["soy lecithin", "artificial flavors", "corn syrup"], certifications: ["USDA Organic", "Fair Trade", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Fair trade organic cacao with minimal clean ingredients." },
    { name: "Endangered Species Dark Chocolate", brand: "Endangered Species", score: 81, category: "chocolate", subcategory: "dark", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["cacao", "cane sugar", "cocoa butter"], avoids: ["artificial flavors", "emulsifiers", "corn syrup"], certifications: ["Fair Trade", "Non-GMO"], whereToFind: ["Target", "Whole Foods", "Amazon", "Walmart"], priceRange: "mid", reason: "Ethically sourced cacao with no artificial flavors or emulsifiers." },
    { name: "Theo Organic Dark Chocolate", brand: "Theo", score: 83, category: "chocolate", subcategory: "dark", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["organic cacao beans", "organic cane sugar", "organic cocoa butter"], avoids: ["soy lecithin", "artificial flavors", "preservatives"], certifications: ["USDA Organic", "Fair Trade", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Seattle-roasted organic chocolate with no soy lecithin." },
    { name: "Eating Evolved Primal Chocolate", brand: "Eating Evolved", score: 85, category: "chocolate", subcategory: "dark", fixes: ["Emulsifier", "Seed Oil", "Added Sugar", "Ultra-Processed"], keyIngredients: ["organic cacao", "coconut sugar"], avoids: ["soy lecithin", "refined sugar", "seed oils"], certifications: ["Paleo", "Vegan", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Paleo chocolate with coconut sugar and no soy or seed oils." },
    { name: "Lily's Dark Chocolate", brand: "Lily's", score: 74, category: "chocolate", subcategory: "dark", fixes: ["Added Sugar", "Ultra-Processed"], keyIngredients: ["cocoa", "erythritol", "stevia"], avoids: ["sugar", "corn syrup", "artificial flavors"], certifications: ["Non-GMO", "Gluten-Free", "Keto"], whereToFind: ["Target", "Walmart", "Amazon", "Kroger"], priceRange: "mid", reason: "Sweetened with stevia and erythritol — no added sugar." },
    { name: "Pascha Organic Dark Chocolate", brand: "Pascha", score: 82, category: "chocolate", subcategory: "dark", fixes: ["Emulsifier", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["organic cacao mass", "organic cane sugar"], avoids: ["soy", "dairy", "tree nuts", "gluten"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Allergy-friendly dark chocolate free from top 8 allergens." },
    { name: "Taza Chocolate Mexicano", brand: "Taza", score: 80, category: "chocolate", subcategory: "dark", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["organic cacao", "organic cane sugar"], avoids: ["soy lecithin", "artificial flavors", "emulsifiers"], certifications: ["USDA Organic", "Non-GMO", "Fair Trade"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Stone-ground Mexican-style chocolate with bold cacao flavor." },
  ],
  popcorn: [
    { name: "Lesser Evil Organic Popcorn", brand: "Lesser Evil", score: 83, category: "popcorn", subcategory: "plain", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["organic popcorn", "coconut oil", "himalayan salt"], avoids: ["canola oil", "artificial colors", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Popped in coconut oil with Himalayan salt and no seed oils." },
    { name: "Boom Chicka Pop Sea Salt", brand: "Angie's", score: 77, category: "popcorn", subcategory: "plain", fixes: ["Ultra-Processed", "Artificial Dye"], keyIngredients: ["popcorn", "sunflower oil", "sea salt"], avoids: ["artificial colors", "corn syrup", "MSG"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "budget", reason: "Simple popcorn with sunflower oil and sea salt." },
    { name: "Quinn Microwave Popcorn", brand: "Quinn", score: 81, category: "popcorn", subcategory: "plain", fixes: ["Ultra-Processed", "Preservative", "Seed Oil"], keyIngredients: ["organic popcorn", "organic coconut oil", "himalayan salt"], avoids: ["PFAS", "canola oil", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "PFAS-free microwave bags with organic coconut oil." },
    { name: "Skinny Pop Original", brand: "Skinny Pop", score: 75, category: "popcorn", subcategory: "plain", fixes: ["Ultra-Processed", "Artificial Dye"], keyIngredients: ["popcorn", "sunflower oil", "salt"], avoids: ["artificial colors", "preservatives", "MSG"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "budget", reason: "Three ingredients: popcorn, oil, and salt — cleaner than most." },
    { name: "Eliza's Organics Truffle Popcorn", brand: "Eliza's", score: 79, category: "popcorn", subcategory: "flavored", fixes: ["Seed Oil", "Ultra-Processed", "Artificial Dye"], keyIngredients: ["organic popcorn", "olive oil", "truffle salt"], avoids: ["canola oil", "artificial flavors", "preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Gourmet organic popcorn with olive oil and real truffle salt." },
    { name: "G.H. Cretors Chicago Mix", brand: "G.H. Cretors", score: 73, category: "popcorn", subcategory: "flavored", fixes: ["Ultra-Processed"], keyIngredients: ["popcorn", "cane sugar", "real cheese"], avoids: ["artificial flavors", "corn syrup", "MSG"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Costco", "Amazon"], priceRange: "mid", reason: "Real cheese and cane sugar with no artificial flavors." },
    { name: "Angie's BOOMCHICKAPOP Kettle Corn", brand: "Angie's", score: 74, category: "popcorn", subcategory: "kettle", fixes: ["Ultra-Processed", "Artificial Dye"], keyIngredients: ["popcorn", "cane sugar", "sunflower oil", "sea salt"], avoids: ["artificial colors", "artificial flavors", "corn syrup"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco"], priceRange: "budget", reason: "Kettle corn with cane sugar instead of corn syrup." },
    { name: "Trader Joe's Organic Popcorn", brand: "Trader Joe's", score: 80, category: "popcorn", subcategory: "plain", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic popcorn", "organic coconut oil", "sea salt"], avoids: ["canola oil", "artificial flavors", "preservatives"], certifications: ["USDA Organic"], whereToFind: ["Trader Joe's"], priceRange: "budget", reason: "Affordable organic popcorn with coconut oil." },
  ],
  "ice cream": [
    { name: "Coconut Bliss Vanilla Island", brand: "Coconut Bliss", score: 81, category: "ice cream", subcategory: "coconut", fixes: ["Emulsifier", "Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic coconut cream", "organic agave", "organic vanilla"], avoids: ["gums", "artificial colors", "corn syrup"], certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Organic coconut cream ice cream with no gums or emulsifiers." },
    { name: "So Delicious Cashewmilk Ice Cream", brand: "So Delicious", score: 76, category: "ice cream", subcategory: "dairy", fixes: ["Artificial Dye", "Artificial Sweetener"], keyIngredients: ["organic cashew milk", "organic cane sugar", "coconut oil"], avoids: ["artificial colors", "artificial sweeteners", "HFCS"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Target", "Walmart", "Whole Foods"], priceRange: "mid", reason: "Organic cashew cream base with no artificial colors or sweeteners." },
    { name: "NadaMoo! Vanilla Bean", brand: "NadaMoo!", score: 77, category: "ice cream", subcategory: "coconut", fixes: ["Emulsifier", "Ultra-Processed"], keyIngredients: ["organic coconut cream", "organic cane sugar", "vanilla bean"], avoids: ["guar gum", "artificial flavors", "corn syrup"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Sprouts", "Target"], priceRange: "mid", reason: "Organic coconut cream ice cream with real vanilla bean." },
    { name: "Brave Robot Animal-Free Ice Cream", brand: "Brave Robot", score: 73, category: "ice cream", subcategory: "dairy", fixes: ["Ultra-Processed"], keyIngredients: ["animal-free whey protein", "coconut oil", "cane sugar"], avoids: ["animal dairy", "artificial colors", "HFCS"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Amazon"], priceRange: "mid", reason: "Real dairy protein made without cows — animal-free ice cream." },
    { name: "Three Twins Organic Ice Cream", brand: "Three Twins", score: 81, category: "ice cream", subcategory: "dairy", fixes: ["Ultra-Processed", "Artificial Dye", "Preservative"], keyIngredients: ["organic cream", "organic milk", "organic cane sugar"], avoids: ["artificial colors", "preservatives", "corn syrup"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target"], priceRange: "mid", reason: "USDA Organic with simple dairy and no artificial additives." },
    { name: "Jeni's Splendid Ice Cream", brand: "Jeni's", score: 75, category: "ice cream", subcategory: "dairy", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["grass-fed milk", "cream", "cane sugar"], avoids: ["artificial colors", "corn syrup", "artificial stabilizers"], certifications: ["Non-GMO"], whereToFind: ["Whole Foods", "Target", "Jeni's stores"], priceRange: "premium", reason: "Small-batch with grass-fed dairy and no artificial stabilizers." },
    { name: "Nounós Crème Yogurt Ice Cream", brand: "Nounós", score: 79, category: "ice cream", subcategory: "dairy", fixes: ["Ultra-Processed", "Artificial Dye"], keyIngredients: ["grass-fed milk", "cream", "live cultures"], avoids: ["artificial colors", "gums", "corn syrup"], certifications: ["Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "premium", reason: "Yogurt-based ice cream with live cultures and grass-fed dairy." },
    { name: "Eclipse Plant-Based Ice Cream", brand: "Eclipse", score: 74, category: "ice cream", subcategory: "oat", fixes: ["Artificial Dye", "Artificial Sweetener"], keyIngredients: ["oat milk", "corn starch", "coconut oil"], avoids: ["artificial colors", "artificial sweeteners", "soy"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Oat-based ice cream that tastes like dairy without artificial additives." },
  ],
  candy: [
    { name: "Unreal Dark Chocolate Gems", brand: "Unreal", score: 76, category: "candy", subcategory: "chocolate", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["dark chocolate", "cane sugar", "coconut oil"], avoids: ["artificial dyes", "corn syrup", "synthetic flavors"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Whole Foods", "Amazon"], priceRange: "mid", reason: "No artificial dyes, corn syrup, or synthetic flavors." },
    { name: "YumEarth Organic Fruit Snacks", brand: "YumEarth", score: 73, category: "candy", subcategory: "gummy", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic fruit juice", "organic cane sugar", "pectin"], avoids: ["artificial dyes", "HFCS", "gelatin"], certifications: ["USDA Organic", "Non-GMO", "Vegan", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Amazon"], priceRange: "budget", reason: "USDA Organic with real fruit juice and no artificial dyes." },
    { name: "SmartSweets Gummy Bears", brand: "SmartSweets", score: 69, category: "candy", subcategory: "gummy", fixes: ["Added Sugar", "Artificial Dye"], keyIngredients: ["soluble corn fiber", "allulose", "pectin"], avoids: ["artificial colors", "sugar alcohols", "gelatin"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Amazon"], priceRange: "mid", reason: "Low sugar with plant-based sweeteners and no artificial colors." },
    { name: "Surf Sweets Organic Gummy Bears", brand: "Surf Sweets", score: 72, category: "candy", subcategory: "gummy", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic fruit juice", "organic cane sugar", "organic tapioca syrup"], avoids: ["artificial colors", "corn syrup", "gelatin"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Organic gummy bears with fruit juice colors — no artificial dyes." },
    { name: "Cocomels Coconut Milk Caramels", brand: "Cocomels", score: 75, category: "candy", subcategory: "caramel", fixes: ["Artificial Dye", "Ultra-Processed", "Emulsifier"], keyIngredients: ["coconut cream", "coconut sugar", "sea salt"], avoids: ["dairy", "artificial colors", "corn syrup"], certifications: ["USDA Organic", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic coconut caramels with no dairy or artificial colors." },
    { name: "Hu Kitchen Chocolate Covered Hunks", brand: "Hu Kitchen", score: 78, category: "candy", subcategory: "chocolate", fixes: ["Emulsifier", "Seed Oil", "Ultra-Processed"], keyIngredients: ["organic cacao", "coconut sugar", "cashews"], avoids: ["soy lecithin", "seed oils", "refined sugar"], certifications: ["Paleo", "Non-GMO", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Dark chocolate covered nuts with no soy lecithin or seed oils." },
    { name: "Justin's Dark Chocolate Peanut Butter Cups", brand: "Justin's", score: 74, category: "candy", subcategory: "chocolate", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["dark chocolate", "organic peanut butter"], avoids: ["artificial colors", "HFCS", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Walmart", "Whole Foods", "Amazon"], priceRange: "mid", reason: "Organic peanut butter cups with dark chocolate and no artificial dyes." },
    { name: "Lovely Organic Lollipops", brand: "Lovely", score: 70, category: "candy", subcategory: "hard candy", fixes: ["Artificial Dye", "Ultra-Processed"], keyIngredients: ["organic cane sugar", "organic brown rice syrup", "natural flavors"], avoids: ["artificial dyes", "corn syrup", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Whole Foods", "Amazon"], priceRange: "budget", reason: "Organic lollipops colored with fruit and vegetable extracts." },
  ],
  juice: [
    { name: "Lakewood Organic Pure Juice", brand: "Lakewood", score: 86, category: "juice", subcategory: "cold-pressed", fixes: ["Added Sugar", "Preservative", "Ultra-Processed"], keyIngredients: ["organic fruits", "organic vegetables"], avoids: ["sugar", "preservatives", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "100% organic pressed juice with no added sugar or preservatives." },
    { name: "Suja Organic Cold-Pressed Juice", brand: "Suja", score: 84, category: "juice", subcategory: "cold-pressed", fixes: ["Added Sugar", "Preservative", "Ultra-Processed"], keyIngredients: ["organic cold-pressed fruits", "organic vegetables"], avoids: ["sugar", "preservatives", "artificial flavors"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Target", "Whole Foods", "Costco", "Amazon"], priceRange: "mid", reason: "Cold-pressed organic fruits and vegetables — nothing artificial." },
    { name: "Evolution Fresh Cold-Pressed Juice", brand: "Evolution Fresh", score: 79, category: "juice", subcategory: "cold-pressed", fixes: ["Added Sugar", "Preservative"], keyIngredients: ["cold-pressed fruits", "cold-pressed vegetables"], avoids: ["added sugars", "artificial flavors", "preservatives"], certifications: ["Non-GMO"], whereToFind: ["Target", "Whole Foods", "Starbucks"], priceRange: "mid", reason: "No added sugars or artificial flavors, high-pressure processed." },
    { name: "R.W. Knudsen Organic Juice", brand: "R.W. Knudsen", score: 81, category: "juice", subcategory: "cold-pressed", fixes: ["Added Sugar", "Ultra-Processed"], keyIngredients: ["organic fruit juice"], avoids: ["added sugar", "artificial flavors", "preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "budget", reason: "Organic fruit juice with no added sugar at an accessible price." },
    { name: "Uncle Matt's Organic OJ", brand: "Uncle Matt's", score: 83, category: "juice", subcategory: "fresh", fixes: ["Added Sugar", "Preservative"], keyIngredients: ["organic oranges"], avoids: ["added sugar", "preservatives", "concentrates"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Publix"], priceRange: "mid", reason: "Organic not-from-concentrate OJ with no added sugar." },
    { name: "Pressed Juicery Greens Juice", brand: "Pressed Juicery", score: 80, category: "juice", subcategory: "cold-pressed", fixes: ["Added Sugar", "Ultra-Processed", "Preservative"], keyIngredients: ["organic kale", "organic celery", "organic lemon"], avoids: ["sugar", "preservatives", "artificial flavors"], certifications: ["Non-GMO", "Vegan"], whereToFind: ["Pressed Juicery stores", "Amazon"], priceRange: "premium", reason: "Cold-pressed greens with no fruit sugar — just vegetables." },
    { name: "Harmless Harvest Organic Coconut Water", brand: "Harmless Harvest", score: 82, category: "juice", subcategory: "coconut", fixes: ["Added Sugar", "Ultra-Processed", "Preservative"], keyIngredients: ["organic young coconut water"], avoids: ["sugar", "preservatives", "concentrate"], certifications: ["USDA Organic", "Non-GMO", "Fair Trade"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Raw organic coconut water with no added sugar or heat processing." },
    { name: "GT's Organic Kombucha", brand: "GT's", score: 78, category: "juice", subcategory: "fermented", fixes: ["Added Sugar", "Ultra-Processed", "Preservative"], keyIngredients: ["organic tea", "organic sugar", "live cultures"], avoids: ["artificial flavors", "preservatives", "HFCS"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Kroger", "Amazon"], priceRange: "mid", reason: "Raw organic kombucha with live cultures and minimal sugar." },
  ],
  "cooking oil": [
    { name: "Chosen Foods Avocado Oil", brand: "Chosen Foods", score: 89, category: "cooking oil", subcategory: "avocado", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil"], avoids: ["canola oil", "soybean oil", "additives"], certifications: ["Non-GMO", "Keto", "Paleo"], whereToFind: ["Costco", "Target", "Amazon", "Walmart"], priceRange: "mid", reason: "Naturally refined avocado oil with a high smoke point and no additives." },
    { name: "Nutiva Organic Coconut Oil", brand: "Nutiva", score: 86, category: "cooking oil", subcategory: "coconut", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic virgin coconut oil"], avoids: ["refining chemicals", "bleaching", "deodorizing"], certifications: ["USDA Organic", "Non-GMO", "Fair Trade"], whereToFind: ["Whole Foods", "Target", "Amazon", "Costco"], priceRange: "mid", reason: "USDA Organic virgin coconut oil with no refining or bleaching." },
    { name: "California Olive Ranch Extra Virgin", brand: "California Olive Ranch", score: 88, category: "cooking oil", subcategory: "olive", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["California-grown olives"], avoids: ["seed oil blending", "deodorizing", "additives"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Kroger", "Amazon"], priceRange: "mid", reason: "100% California-grown olives, cold-pressed with no seed oil blending." },
    { name: "Primal Kitchen Avocado Oil", brand: "Primal Kitchen", score: 87, category: "cooking oil", subcategory: "avocado", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil"], avoids: ["canola oil", "seed oils", "additives"], certifications: ["Non-GMO", "Paleo", "Keto"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Cold-pressed avocado oil with no seed oil blending." },
    { name: "Cobram Estate Extra Virgin Olive Oil", brand: "Cobram Estate", score: 85, category: "cooking oil", subcategory: "olive", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["Australian-grown olives"], avoids: ["seed oils", "additives", "blending"], certifications: ["Non-GMO"], whereToFind: ["Target", "Walmart", "Amazon"], priceRange: "mid", reason: "Award-winning Australian olive oil with verified purity." },
    { name: "Spectrum Organic Sesame Oil", brand: "Spectrum", score: 80, category: "cooking oil", subcategory: "specialty", fixes: ["Ultra-Processed"], keyIngredients: ["organic sesame seeds"], avoids: ["additives", "preservatives", "hexane"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Expeller-pressed organic sesame oil — no hexane extraction." },
    { name: "Carrington Farms Organic Ghee", brand: "Carrington Farms", score: 84, category: "cooking oil", subcategory: "specialty", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic grass-fed butter"], avoids: ["seed oils", "lactose", "casein"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Walmart", "Amazon", "Costco"], priceRange: "mid", reason: "Grass-fed organic ghee — lactose-free and high smoke point." },
    { name: "La Tourangelle Avocado Oil", brand: "La Tourangelle", score: 83, category: "cooking oil", subcategory: "avocado", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil"], avoids: ["canola oil", "soybean oil", "additives"], certifications: ["Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Artisan avocado oil with a neutral flavor for all cooking." },
  ],
  noodles: [
    { name: "Jovial Organic Brown Rice Pasta", brand: "Jovial", score: 88, category: "noodles", subcategory: "rice", fixes: ["Ultra-Processed"], keyIngredients: ["organic brown rice"], avoids: ["additives", "corn", "wheat"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "mid", reason: "Single ingredient organic brown rice — gluten-free with no additives." },
    { name: "Banza Chickpea Pasta", brand: "Banza", score: 84, category: "noodles", subcategory: "legume", fixes: ["Ultra-Processed"], keyIngredients: ["chickpea flour", "tapioca", "pea protein"], avoids: ["enriched flour", "artificial colors"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Whole Foods", "Amazon"], priceRange: "mid", reason: "High protein chickpea pasta with no artificial ingredients." },
    { name: "Lotus Foods Organic Ramen", brand: "Lotus Foods", score: 81, category: "noodles", subcategory: "rice", fixes: ["Ultra-Processed", "Preservative", "Seed Oil"], keyIngredients: ["organic brown rice", "organic millet"], avoids: ["MSG", "artificial flavors", "palm oil"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic rice ramen with no MSG or artificial flavors." },
    { name: "Tinkyada Brown Rice Pasta", brand: "Tinkyada", score: 82, category: "noodles", subcategory: "rice", fixes: ["Ultra-Processed"], keyIngredients: ["brown rice", "rice bran"], avoids: ["wheat", "corn", "additives"], certifications: ["Gluten-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "budget", reason: "Rice pasta with great texture and no additives." },
    { name: "Explore Cuisine Edamame Noodles", brand: "Explore Cuisine", score: 83, category: "noodles", subcategory: "legume", fixes: ["Ultra-Processed"], keyIngredients: ["organic edamame flour"], avoids: ["wheat", "additives", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic edamame noodles with 24g protein per serving." },
    { name: "Mike's Mighty Good Ramen", brand: "Mike's Mighty Good", score: 76, category: "noodles", subcategory: "ramen", fixes: ["Ultra-Processed", "Preservative"], keyIngredients: ["organic wheat", "organic palm oil", "spices"], avoids: ["MSG", "artificial flavors", "preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Organic ramen with no MSG, artificial flavors, or preservatives." },
    { name: "Tolerant Red Lentil Pasta", brand: "Tolerant", score: 86, category: "noodles", subcategory: "legume", fixes: ["Ultra-Processed"], keyIngredients: ["organic red lentil flour"], avoids: ["wheat", "additives", "preservatives"], certifications: ["USDA Organic", "Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Whole Foods", "Amazon"], priceRange: "mid", reason: "Single-ingredient organic lentil pasta with 25g protein." },
    { name: "Cappello's Almond Flour Fettuccine", brand: "Cappello's", score: 80, category: "noodles", subcategory: "grain-free", fixes: ["Ultra-Processed", "Seed Oil"], keyIngredients: ["almond flour", "tapioca flour", "eggs"], avoids: ["grains", "seed oils", "preservatives"], certifications: ["Paleo", "Grain-Free", "Non-GMO"], whereToFind: ["Whole Foods", "Sprouts", "Amazon"], priceRange: "premium", reason: "Grain-free almond flour pasta with no seed oils." },
  ],
  snack: [
    { name: "Simple Mills Snack Crackers", brand: "Simple Mills", score: 84, category: "snack", subcategory: "crackers", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["almond flour", "sunflower seeds", "flax"], avoids: ["canola oil", "soybean oil", "artificial flavors"], certifications: ["Non-GMO", "Grain-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Almond flour base with no seed oils or artificial additives." },
    { name: "Hu Kitchen Grain-Free Crackers", brand: "Hu Kitchen", score: 79, category: "snack", subcategory: "crackers", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["cassava flour", "olive oil", "seeds"], avoids: ["canola oil", "sugar", "soy"], certifications: ["Paleo", "Grain-Free", "Vegan"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Paleo-friendly with cassava flour and clean ingredients." },
    { name: "RXBAR Protein Bar", brand: "RXBAR", score: 86, category: "snack", subcategory: "bar", fixes: ["Seed Oil", "Artificial Sweetener", "Ultra-Processed"], keyIngredients: ["egg whites", "dates", "nuts"], avoids: ["canola oil", "sucralose", "soy protein"], certifications: ["Non-GMO", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "mid", reason: "Minimal ingredients: egg whites, dates, and nuts — no additives." },
    { name: "Larabar Fruit & Nut Bar", brand: "Larabar", score: 88, category: "snack", subcategory: "bar", fixes: ["Seed Oil", "Ultra-Processed", "Added Sugar"], keyIngredients: ["dates", "nuts", "fruit"], avoids: ["oil", "sugar", "artificial sweeteners"], certifications: ["Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Target", "Walmart", "Kroger", "Amazon"], priceRange: "budget", reason: "Just dates, nuts, and fruit — nothing artificial." },
    { name: "Lesser Evil Organic Popcorn", brand: "Lesser Evil", score: 83, category: "snack", subcategory: "popcorn", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["organic popcorn", "coconut oil", "himalayan salt"], avoids: ["canola oil", "artificial colors", "preservatives"], certifications: ["USDA Organic", "Non-GMO"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "mid", reason: "Popped in coconut oil with Himalayan salt — no seed oils." },
    { name: "Siete Grain-Free Tortilla Chips", brand: "Siete", score: 82, category: "snack", subcategory: "chips", fixes: ["Seed Oil", "Ultra-Processed"], keyIngredients: ["avocado oil", "cassava flour", "sea salt"], avoids: ["canola oil", "corn", "soy"], certifications: ["Non-GMO", "Grain-Free", "Gluten-Free"], whereToFind: ["Whole Foods", "Target", "Amazon"], priceRange: "premium", reason: "Grain-free tortilla chips made with avocado oil." },
    { name: "Bare Baked Crunchy Apple Chips", brand: "Bare", score: 85, category: "snack", subcategory: "fruit", fixes: ["Seed Oil", "Ultra-Processed", "Added Sugar"], keyIngredients: ["apples"], avoids: ["oil", "sugar", "preservatives"], certifications: ["Non-GMO", "Gluten-Free", "Vegan"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "mid", reason: "Single-ingredient baked apple chips with no oil or sugar." },
    { name: "That's It Fruit Bar", brand: "That's It", score: 91, category: "snack", subcategory: "fruit", fixes: ["Seed Oil", "Artificial Sweetener", "Ultra-Processed", "Added Sugar"], keyIngredients: ["apples", "mangoes"], avoids: ["oil", "sugar", "preservatives"], certifications: ["Non-GMO", "Vegan", "Paleo", "Gluten-Free"], whereToFind: ["Target", "Walmart", "Costco", "Amazon"], priceRange: "budget", reason: "Two ingredients: real fruit pressed into a bar. Nothing else." },
  ],
};

// ── Category Inference ─────────────────────────────────────────────
export function inferCategory(name: string, brand?: string): string {
  const n = (name + " " + (brand || "")).toLowerCase();
  if (/energy|monster|red\s*bull|celsius|bang|reign|rockstar|g\s*fuel|zoa/i.test(n)) return "energy drinks";
  if (/frozen\s*(meal|dinner|entrée|entree|pizza|burrito)|lean\s*cuisine|stouffer|amy.*kitchen|hot\s*pocket/i.test(n)) return "frozen meals";
  if (/peanut\s*butter|almond\s*butter|nut\s*butter|sun\s*butter|cashew\s*butter/i.test(n)) return "peanut butter";
  if (/dressing|vinaigrette|ranch|caesar/i.test(n)) return "salad dressing";
  if (/cooking\s*oil|olive\s*oil|avocado\s*oil|coconut\s*oil|canola|vegetable\s*oil/i.test(n)) return "cooking oil";
  if (/popcorn|pop corn|kettle corn|kettlecorn|smartfood|boom chicka|lesser evil|skinny pop|skinnypop|angie|quinn popcorn/i.test(n)) return "popcorn";
  if (/chip|crisp|frito|dorito|cheeto/i.test(n)) return "chips";
  if (/cereal|granola|flake|crunch|cheerio|loop|oatmeal/i.test(n)) return "cereal";
  if (/cracker|pretzel|goldfish/i.test(n)) return "crackers";
  if (/yogurt|yoghurt|kefir/i.test(n)) return "yogurt";
  if (/soda|cola|sprite|fanta|mountain dew|dr pepper|\bpop\b/i.test(n)) return "soda";
  if (/juice/i.test(n)) return "juice";
  if (/cookie|oreo|biscuit/i.test(n)) return "cookies";
  if (/candy|gumm|skittle|starburst|sour/i.test(n)) return "candy";
  if (/ice\s*cream|gelato/i.test(n)) return "ice cream";
  if (/bread|bun|bagel|muffin|toast|tortilla|wrap/i.test(n)) return "bread";
  if (/sauce|ketchup|mustard|mayo|bbq/i.test(n)) return "sauce";
  if (/bar|cliff|kind|rxbar|protein\s*bar|granola\s*bar|snack\s*bar/i.test(n)) return "bars";
  if (/noodle|ramen|pasta|mac.*cheese/i.test(n)) return "noodles";
  if (/milk|oat.*milk|almond.*milk/i.test(n)) return "milk";
  if (/chocolate|cocoa|hazelnut|nutella|spread/i.test(n)) return "chocolate";
  if (/frozen/i.test(n)) return "frozen meals";
  return "snack";
}

// ── Dietary Preference Mapping ─────────────────────────────────────
const PREF_TO_CERT: Record<string, string[]> = {
  "gluten": ["Gluten-Free"],
  "dairy": ["Vegan"],
  "seed-oils": [],
  "artificial-dyes": [],
  "artificial-sweeteners": [],
  "preservatives": [],
};

const PREF_TO_FIX: Record<string, string> = {
  "seed-oils": "Seed Oil",
  "artificial-dyes": "Artificial Dye",
  "artificial-sweeteners": "Artificial Sweetener",
  "preservatives": "Preservative",
};

// ── Intelligent Matching ───────────────────────────────────────────
export function getAlternatives(product: ProductResult): AlternativeProduct[] {
  const category = inferCategory(product.name, product.brand);
  const flaggedCategories = [...new Set(product.flagged.map((f) => f.category))];

  // Get all alternatives in this category, fall back to snack
  const categoryAlts = ALT_DB[category] || ALT_DB.snack;
  if (!categoryAlts || categoryAlts.length === 0) return [];

  // Load user dietary preferences
  let userPrefs: string[] = [];
  try {
    const stored = localStorage.getItem("pure_dietary_prefs");
    if (stored) userPrefs = JSON.parse(stored);
  } catch {}

  // Map user prefs to certification and fix boosts
  const prefCerts = userPrefs.flatMap((p) => PREF_TO_CERT[p] || []);
  const prefFixes = userPrefs.map((p) => PREF_TO_FIX[p]).filter(Boolean);

  // Score each alternative by relevance
  const scored = categoryAlts.map((alt) => {
    let relevance = alt.score;

    // +30 if it fixes ALL flagged categories from scanned product
    if (flaggedCategories.length > 0 && flaggedCategories.every((f) => alt.fixes.includes(f))) {
      relevance += 30;
    }

    // +20 if it fixes the primary flagged category
    if (flaggedCategories.length > 0 && alt.fixes.includes(flaggedCategories[0])) {
      relevance += 20;
    }

    // +10 for each additional flagged category it fixes
    const additionalFixes = flaggedCategories.slice(1).filter((f) => alt.fixes.includes(f)).length;
    relevance += additionalFixes * 10;

    // +15 if certifications match user dietary preferences
    if (prefCerts.length > 0 && prefCerts.some((c) => alt.certifications.includes(c))) {
      relevance += 15;
    }

    // +10 if it fixes categories matching user dietary preferences
    if (prefFixes.length > 0 && prefFixes.some((f) => alt.fixes.includes(f))) {
      relevance += 10;
    }

    return { ...alt, relevanceScore: relevance };
  });

  // Deduplicate by name, sort by relevance, return top 6
  const seen = new Set<string>();
  return scored
    .sort((a, b) => b.relevanceScore - a.relevanceScore)
    .filter((alt) => {
      if (seen.has(alt.name)) return false;
      seen.add(alt.name);
      return true;
    })
    .slice(0, 6);
}

export { ALT_DB };
